/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.jsrois;

import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.List;

public class FileSizeFormatter {
    public String getSize(Long bytes) {
        var format = formats.stream()
                .filter(fmt -> fmt.bytes() < bytes)
                .findFirst()
                .orElse(new SizeFormat(1.0, "B"));

        var decimal = new DecimalFormat("0.##");
        decimal.setRoundingMode(RoundingMode.HALF_UP);

        return String.format("%s %s",
                decimal.format(bytes / format.bytes()).toString(),
                format.symbol());
    }

    private List<SizeFormat> formats = List.of(
            new SizeFormat(1e12, "TB"),
            new SizeFormat(1e9, "GB"),
            new SizeFormat(1e6, "MB"),
            new SizeFormat(1e3, "kB"));
}
