/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.jsrois;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {

    private FileSizeFormatter formatter;

    @BeforeEach
    void setup() {
        formatter = new FileSizeFormatter();
    }

    @Test
    void formatsBytes() {
        assertEquals("213 B", formatter.getSize(213L));
    }

    @Test
    void formatKiloBytes() {
        assertEquals("1.35 kB", formatter.getSize(1350L));
    }

    @Test
    void formatMegaBytes() {
        assertEquals("9.78 MB", formatter.getSize(9776100L));
    }

    @Test
    void formatGigaBytes() {
        assertEquals("9.66 GB", formatter.getSize(9663234244L));
    }

    @Test
    void formatTeraBytes() {
        assertEquals("3.46 TB", formatter.getSize(3463234244244L));
    }


}
